# Generated by Django 4.0.5 on 2025-01-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=50)),
                ('test_code', models.CharField(max_length=50, unique=True)),
                ('test_name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('normal_range', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('test_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
