# Generated by Django 4.0.5 on 2023-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='userCreatorName',
            field=models.TextField(blank=True, default='--', max_length=50, null=True),
        ),
    ]
