# Generated by Django 4.0.5 on 2024-02-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patients_iscompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Womacs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_id', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('isempty', models.BooleanField(default=True)),
                ('userCreatorId', models.IntegerField(blank=True, null=True)),
                ('kodmeli', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('name', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('surname', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('pain_walk', models.IntegerField(default=0)),
                ('pain_stair', models.IntegerField(default=0)),
                ('pain_nocturnal', models.IntegerField(default=0)),
                ('pain_rest', models.IntegerField(default=0)),
                ('pain_weight', models.IntegerField(default=0)),
                ('stiff_morning', models.IntegerField(default=0)),
                ('stiff_later', models.IntegerField(default=0)),
                ('Physical_stair_descend', models.IntegerField(default=0)),
                ('physical_stair_ascend', models.IntegerField(default=0)),
                ('physical_rising_sitting', models.IntegerField(default=0)),
                ('physical_standing', models.IntegerField(default=0)),
                ('physical_bending', models.IntegerField(default=0)),
                ('physical_walking_flat', models.IntegerField(default=0)),
                ('physical_getting_in_car', models.IntegerField(default=0)),
                ('physical_shopping', models.IntegerField(default=0)),
                ('physical_socks_in', models.IntegerField(default=0)),
                ('physical_lying_bed', models.IntegerField(default=0)),
                ('physical_socks_out', models.IntegerField(default=0)),
                ('physical_rising_bed', models.IntegerField(default=0)),
                ('physical_bath', models.IntegerField(default=0)),
                ('physical_sitting', models.IntegerField(default=0)),
                ('physical_toilet', models.IntegerField(default=0)),
                ('physical_home_heavy', models.IntegerField(default=0)),
                ('physical_home_light', models.IntegerField(default=0)),
                ('womac_score', models.IntegerField(default=0)),
                ('womacdate', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('womactime', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patients')),
            ],
        ),
    ]
