# Generated by Django 4.0.5 on 2024-05-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_womacs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_id', models.CharField(default='', max_length=100)),
                ('sample_code', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('kodmeli', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('birth', models.CharField(default='', max_length=50)),
                ('is_imported', models.BooleanField(default=False)),
                ('sample_date', models.CharField(default='', max_length=50)),
                ('expected_result_date', models.CharField(default='', max_length=50)),
                ('result_date', models.CharField(default='', max_length=50)),
                ('origin_lab', models.CharField(default='', max_length=50)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('receiver_lab', models.CharField(default='', max_length=50)),
                ('emergent_status', models.CharField(default='', max_length=50)),
                ('sample_hour', models.CharField(default='', max_length=50)),
                ('result_hour', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idId', models.CharField(default='', max_length=50)),
                ('testCode', models.CharField(default='', max_length=50)),
                ('testName', models.CharField(default='', max_length=50)),
                ('unit', models.CharField(default='', max_length=50)),
                ('testCost1', models.CharField(default='', max_length=50)),
                ('testCost2', models.CharField(default='', max_length=50)),
                ('testCost3', models.CharField(default='', max_length=50)),
                ('testCost4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sampleCode', models.CharField(default='', max_length=50)),
                ('idId', models.CharField(default='', max_length=50)),
                ('testCode', models.CharField(default='', max_length=50)),
                ('testResult', models.CharField(default='', max_length=50)),
                ('dateReceived', models.CharField(default='', max_length=50)),
                ('dateResultExpect', models.CharField(default='', max_length=50)),
                ('dateResultSent', models.CharField(default='', max_length=50)),
                ('sampleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.samples')),
            ],
        ),
        migrations.RemoveField(
            model_name='constanttables',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='dashtables',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='followfems',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='followhums',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='followrads',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='haristables',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='imagingtables',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='injurytables',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='note',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='sftables',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatmenttables',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vastables',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='womacs',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ca_art',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ca_mult',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ca_sim',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ex_rad_dor',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ex_rad_no',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ex_rad_vol',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ex_radw',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ex_ul_mu',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ex_ul_si',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_ex_ul_st',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_pa_rad_fra',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_pa_rad_inv',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_pa_rad_mul',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_pa_rad_si',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_pa_rad_sim',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_pa_rad_wit',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ao_pa_radvol',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='date_modif',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='domhand',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='edu',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_head_1',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_head_2',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_head_3',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_head_4',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_inter_1a',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_inter_1b',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_inter_2a',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_inter_2b',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_neck_dis',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_neck_non',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_neck_sub',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_neck_trans',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='femor_sub',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='hight',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_four',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_surgi_i',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_surgi_n',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_surgi_tub_disp',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_surgi_tub_g',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_surgi_tub_l',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_surgi_tub_no',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_tuber_gd',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_tuber_gn',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='humer_tuber_l',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='int_job',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='is_ao_set',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='iscompleted',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='job',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='neer',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='reg_type',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='weight',
        ),
        migrations.AddField(
            model_name='patients',
            name='date_created',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='birth',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patients',
            name='id_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='kodmeli',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='userCreatorName',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.DeleteModel(
            name='ConstantTables',
        ),
        migrations.DeleteModel(
            name='DashTables',
        ),
        migrations.DeleteModel(
            name='Followfems',
        ),
        migrations.DeleteModel(
            name='Followhums',
        ),
        migrations.DeleteModel(
            name='Followrads',
        ),
        migrations.DeleteModel(
            name='HarisTables',
        ),
        migrations.DeleteModel(
            name='ImagingTables',
        ),
        migrations.DeleteModel(
            name='InjuryTables',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='SFTables',
        ),
        migrations.DeleteModel(
            name='TreatmentTables',
        ),
        migrations.DeleteModel(
            name='VASTables',
        ),
        migrations.DeleteModel(
            name='Womacs',
        ),
        migrations.AddField(
            model_name='samples',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patients'),
        ),
    ]
