# Generated by Django 4.0.5 on 2024-05-02 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_samples_testinfos_testresults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patients'),
        ),
        migrations.AddField(
            model_name='testresults',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.samples'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='patientId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='sampleId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
