# Generated by Django 4.0.5 on 2024-05-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_samples_patient_testresults_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfos',
            name='k_fani',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testinfos',
            name='k_herfe',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testinfos',
            name='k_total',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testinfos',
            name='normal_range',
            field=models.CharField(default='', max_length=50),
        ),
    ]
