# Generated by Django 4.0.5 on 2024-05-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_testinfos_k_fani_testinfos_k_herfe_testinfos_k_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfos',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
