# Generated by Django 4.0.5 on 2024-05-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_testinfos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfos',
            name='group',
            field=models.CharField(default='', max_length=50),
        ),
    ]
