# Generated by Django 4.0.5 on 2024-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_testinfos_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='userCreatorId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
