# Generated by Django 4.0.5 on 2024-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_samples_usercreatorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='patientId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='sampleId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
