# Generated by Django 4.0.5 on 2024-05-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_samples_patientid_alter_testresults_sampleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testinfos',
            old_name='idId',
            new_name='id_id',
        ),
        migrations.RenameField(
            model_name='testresults',
            old_name='idId',
            new_name='id_id',
        ),
    ]
