# Generated by Django 4.0.5 on 2024-06-14 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_samples_is_confirmed_samples_is_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleLists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_id', models.CharField(default='', max_length=100)),
                ('userCreatorName', models.CharField(default='--', max_length=100)),
                ('name', models.CharField(default='', max_length=50)),
                ('jsonList', models.CharField(default='', max_length=50)),
                ('date_created', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
