# Generated by Django 4.0.5 on 2024-06-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_samplelists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplelists',
            name='jsonList',
            field=models.TextField(default=''),
        ),
    ]
