# Generated by Django 4.0.5 on 2024-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_samplelists_jsonlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='history',
            field=models.TextField(default=''),
        ),
    ]
