# Generated by Django 4.0.5 on 2024-06-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_samples_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_id', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('isempty', models.BooleanField(default=True)),
                ('userCreatorId', models.IntegerField(blank=True, null=True)),
                ('kodmeli', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('name', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('surname', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('file_date', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('file_loc', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('sample_Main_Img', models.FileField(blank=True, null=True, upload_to='files/')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.samples')),
            ],
        ),
    ]
