# Generated by Django 4.0.5 on 2024-06-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_imagingtables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagingTables',
            new_name='FileTables',
        ),
    ]
