# Generated by Django 4.0.5 on 2024-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='file_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
