# Generated by Django 4.0.5 on 2024-07-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_usersdetaileds_user_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetaileds',
            name='userCreatorId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
