# Generated by Django 4.0.5 on 2024-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_usersdetaileds_usercreatorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetaileds',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
