# Generated by Django 4.0.5 on 2024-08-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_usersdetaileds_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetables',
            name='use_case',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='normal_range',
            field=models.TextField(default=''),
        ),
    ]
