# Generated by Django 4.0.5 on 2024-08-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_samples_history_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='samples',
            name='sample_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
