# Generated by Django 4.0.5 on 2024-08-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_testresults_testmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
