# Generated by Django 5.1.5 on 2025-01-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_address_userprofile_other_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('manager', 'Manager'), ('admin', 'Administrator')], default='technician', max_length=20),
        ),
    ]
