# Generated by Django 4.0.5 on 2025-01-22 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('labs', '0001_initial'),
        ('tests_definitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported')], default='CREATED', max_length=20)),
                ('emergent_status', models.BooleanField(default=False)),
                ('history', models.TextField(blank=True, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_result_date', models.DateTimeField(blank=True, null=True)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('history_file', models.FileField(blank=True, null=True, upload_to='history_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_samples', to='labs.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='patients.patient')),
                ('receiver_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_samples', to='labs.lab')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=100, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='test_results/')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_tests', to='samples.sample')),
                ('test_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_definitions.testinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('use_case', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='samples.sample')),
            ],
        ),
    ]
