# Generated by Django 5.1.5 on 2025-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_alter_attachment_options_alter_sample_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
