# Generated by Django 5.1.5 on 2025-01-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ['id']},
        ),
    ]
