# Generated by Django 5.1.5 on 2025-01-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_lab_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
